GmailClient.CkEditor/Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CKEditor_ASP.NETCore.Models
{
    public partial class ApplicationUser : IdentityUser
    {
        public ApplicationUser()
        {
            UserArticles = new HashSet<UserArticle>();
        }

        public virtual ICollection<UserArticle> UserArticles { get; set; }
    }
}

GmailClient.CkEditor/Models/ErrorViewModel.cs
using System;

namespace CKEditor_ASP.NETCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GmailClient.CkEditor/Models/UserArticle.cs
using System;

namespace CKEditor_ASP.NETCore.Models
{
    public class UserArticle
    {
        public int ArticleId { get; set; }
        public string UserId { get; set; }
        public string ArticleTitle { get; set; }
        public string Description { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

GmailClient.CkEditor/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using CKEditor_ASP.NETCore.Data;
using CKEditor_ASP.NETCore.Models;

namespace CKEditor_ASP.NETCore.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        //Constructor
        public ArticleController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        /************************************************************************************/
        ////Create Article
        //Method to display 'CreateArticle' page to update or create new article
        [HttpPost]
        public async Task<IActionResult> WriteArticle(UserArticle article)
        {
            string loggedInUserId = _userManager.GetUserId(User);
            article.UserId = loggedInUserId;

            if (article.ArticleId > 0)
                UpdateArticle(article);
            else
                CreateArticle(article);

            if (await SaveChanges())
                return RedirectToAction("AllArticles");
            else
                return View(article);
        }
        [HttpGet]
        public ActionResult<UserArticle> WriteArticle(int? id)
        {
            if (id == null)
            {
                return View(new UserArticle());
            }
            else
            {
                var article = GetArticleById((int)id);
                return View(article);
            }
        }
        //Method to create the Article
        public void CreateArticle(UserArticle article)
        {
            if (article == null)
            {
                throw new ArgumentNullException(nameof(article));
            }
            _context.UserArticles.Add(article);
        }

        //Method to update the Article
        public void UpdateArticle(UserArticle article)
        {
            _context.UserArticles.Update(article);
        }


        /************************************************************************************/
        ////Display all articles
        //Method to display all articles which is received from 'GetAllArticles' method
        public IActionResult AllArticles()
        {
            var articles = GetAllArticles();
            return View(articles);
        }

        //Method to get all articles in the database
        public IEnumerable<UserArticle> GetAllArticles()
        {
            return _context.UserArticles.ToList();
        }


        /************************************************************************************/
        ////Display single article
        //Method to view a single article on SingleArticleView
        public IActionResult SingleArticle(int id)
        {
            var article = GetArticleById(id);

            return View(article);
        }


        /************************************************************************************/
        ////Delete article
        //Method called by the view to delete the Article
        public async Task<IActionResult> RemoveArticle(int id)
        {
            DeleteArticle(id);
            await SaveChanges();
            return RedirectToAction("AllArticles");
        }

        //Method to delete the Article from the database
        public void DeleteArticle(int id)
        {
            _context.UserArticles.Remove(GetArticleById(id));
        }


        /************************************************************************************/
        ////Supportive methods
        //To get Articles by ArticleID
        public UserArticle GetArticleById(int id)
        {
            return _context.UserArticles.FirstOrDefault(a => a.ArticleId == id);
        }

        //Method to save the changes in the database
        public Task<bool> SaveChanges()
        {
            return Task.FromResult(_context.SaveChanges() >= 0);
        }
    }
}

GmailClient.CkEditor/Controllers/HomeController.cs
using CKEditor_ASP.NETCore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CKEditor_ASP.NETCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GmailClient.CkEditor/Views/Article/AllArticles.cshtml
@model IEnumerable<UserArticle>
@{
    ViewData["Title"] = "All Articles";
}

<div class="container-fluid">
    <div class="row d-flex align-items-center justify-content-center">
        <div class="col-md-8">
            <div class="card" style="padding-top:50px">
                <div>
                    @foreach (var article in Model)
                    {
                        <div class="card">
                            <div>
                                @*<a asp-controller="NavBlog" asp-action="PostView" asp-route-id="@article.Id">
                                        @article.Id
                                    </a>*@
                                <a asp-controller="Article" asp-action="SingleArticle" asp-route-id="@article.ArticleId">
                                    <h3>
                                        @article.ArticleTitle
                                    </h3>
                                </a>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <a button type="button" class="btn btn-outline-primary" asp-controller="Article" asp-action="WriteArticle" asp-route-id="@article.ArticleId">
                                        Edit Article
                                    </a>
                                </div>
                                <div class="col">
                                    <a button type="button" class="btn btn-outline-primary" asp-controller="Article" asp-action="RemoveArticle" asp-route-id="@article.ArticleId">
                                        Delete Article
                                    </a>
                                </div>
                            </div>
                        </div>
                       <hr />
                    }
                </div>
            </div>
        </div>
    </div>
</div>

    <style>
        @@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap");

        body {
            background-color: #eee;
            font-family: "Poppins", sans-serif;
            font-weight: 300
        }

        .card {
            border: none
        }

        .ellipsis {
            color: #a09c9c
        }

        hr {
            color: #a09c9c;
            margin-top: 4px;
            margin-bottom: 8px
        }

        .muted-color {
            color: #a09c9c;
            font-size: 13px
        }

        .ellipsis i {
            margin-top: 3px;
            cursor: pointer
        }

        .icons i {
            font-size: 25px
        }

        .icons .fa-heart {
            color: red
        }

        .icons .fa-smile-o {
            color: yellow;
            font-size: 29px
        }

        .rounded-image {
            border-radius: 50% !important;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 50px;
            width: 50px
        }

        .form-control {
            border-radius: 26px
        }

        .fonts {
            position: absolute;
            right: 13px;
            top: 8px;
            color: #a09c9c
        }

        .form-control:focus {
            color: #495057;
            background-color: #fff;
            border-color: #8bbafe;
            outline: 0;
            box-shadow: none
        }
    </style>

GmailClient.CkEditor/Views/Article/SingleArticle.cshtml
@{
    ViewData["Title"] = Model.ArticleTitle;
}

<div class="container-fluid">
    <div class="row d-flex align-items-center justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="d-flex flex-row align-items-center">
                    <p class="text-primary" style="margin-top:30px;">created: @Model.DateTimeCreated</p>
                </div>
                <div><h1 style="text-decoration: underline;text-align: center">@Model.ArticleTitle</h1></div>
                <div style="padding-left:100px;padding-right:100px;">@Html.Raw(@Model.Description)</div>
            </div>
        </div>

    </div>
</div>

<style>
    body {
        background-color: #eee;
        font-family: "Poppins", sans-serif;
        font-weight: 300;
        text-align: justify;
    }

    .card {
        border: solid;
        border-color: darkgray;
        background-color: snow;
    }
</style>

GmailClient.CkEditor/Views/Article/WriteArticle.cshtml
@model UserArticle

@{
    ViewData["Title"] = "Write Articles";
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/ckeditor/ckeditor.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

<div class="card" style="padding:10px 50px 50px 50px">

    <h3>Write your Article Here</h3>

    <div>
        <form asp-controller="Article" asp-action="WriteArticle" method="post">
            @Html.AntiForgeryToken()
            <input asp-for="ArticleId" type="hidden" />
            <input asp-for="UserId" type="hidden" />
            <div ass="col-md-10">
                <textarea style="border-color:grey;" asp-for="ArticleTitle" id="ArticleTitle" name="ArticleTitle" cols="70" placeholder="Add Title"></textarea>
            </div>
            <div ass="col-md-10">
                <textarea asp-for="Description" id="Description" class="ckeditor" name="Description" rows="200"></textarea>
            </div>
            <div style="padding-top:10px">
                <button class="btn btn-outline-primary" type="submit" value="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
<style>
    body {
        background-color: #eee;
        font-family: "Poppins", sans-serif;
        font-weight: 300
    }
</style>


<script>
    $(document).ready(function () {
        CKEDITOR.replace('#Description');
    });
</script>

GmailClient.CkEditor/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <br />
    <br />
    <h4 class="upload-file-link text-center ">
        <a asp-controller="Article" asp-action="WriteArticle">Go to Editor</a>
    </h4>
</div>

<style>
    .upload-file-link {
        margin-top: 100px;
    }

    .upload-file-link a {
        border-radius: 5px;
        background-color: rebeccapurple;
        color: white;
        padding: 5px 10px;
        width: 300px;
        text-decoration: none;
    }

    .upload-file-link a:hover {
        text-decoration: none;
        background-color: grey;
        color: white;
    }
</style>

GmailClient.CkEditor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CKEditor_ASP.NETCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CKEditor_ASP.NETCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="AllArticles">AllArticles</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="WriteArticle">WriteArticle</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CKEditor_ASP.NETCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>