GmailClient.Web/Controllers/EmailSenderController.cs
using System.Threading.Tasks;
using GmailClient.Models;
using Microsoft.AspNetCore.Mvc;

namespace GmailClient.Web.Controllers
{

    public class EmailSenderController : Controller
    {
        private readonly IMailService _emailSender;
        

        public EmailSenderController(IMailService emailSender)
        {
            this._emailSender = emailSender;
           
        }

        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Contact(MailRequest contact)
        {


            ViewData["Message"] = null;
            ViewData["Error"] = null;

            if (ModelState.IsValid)
            {
                

                await _emailSender.SendEmailAsync(contact);



                ViewData["message_color"] = "green";
                ViewData["Message"] = "*Your Message Has Been Sent.";
            }
            else
            {
                ViewData["message_color"] = "red";
                ViewData["Message"] = "*Please complete the required fields";
            }

            ModelState.Clear();

            return View(contact);
        }


        //[HttpPost("welcome")]
        //public async Task<IActionResult> SendWelcomeMail(WelcomeRequest request)
        //{
        //    try
        //    {
        //        await _emailSender.SendWelcomeEmailAsync(request);

        //        return View();
        //    }
        //    catch (Exception ex)
        //    {
        //        throw;
        //    }
        //}

    }

    //
    //[Route("api/[controller]")]
    //[ApiController]
    //public class EmailSenderController : ControllerBase
    //{
    //    private readonly IEmailSender _emailSender;
    //    public EmailSenderController(IEmailSender emailSender)
    //    {
    //        this._emailSender = emailSender;
    //    }
    //    [HttpPost("send")]
    //    public async Task<IActionResult> SendMail([FromForm] MailRequest request)
    //    {
    //        try
    //        {
    //            await _emailSender.SendEmailAsync(request);
    //            return Ok();
    //        }
    //        catch (Exception ex)
    //        {
    //            throw;
    //        }

    //    }


    //    [HttpPost("welcome")]
    //    public async Task<IActionResult> SendWelcomeMail([FromForm] WelcomeRequest request)
    //    {
    //        try
    //        {
    //            await _emailSender.SendWelcomeEmailAsync(request);
    //            return Ok();
    //        }
    //        catch (Exception ex)
    //        {
    //            throw;
    //        }
    //    }

    //}
}

GmailClient.Web/Controllers/GmailServiceController.cs
using System.Threading.Tasks;
using GmailClient.Services;
using Microsoft.AspNetCore.Mvc;

namespace GmailClient.Web.Controllers
{
    public class GmailServiceController : Controller
    {
        // GET: GmailServiceController
        public async Task<ActionResult> Index()
        {
            var gmailService = new GmailService(null);
            var emails = await gmailService.GetEmails();

            return View(emails);
        }

    }
}

GmailClient.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GmailAPIAsp1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GmailAPIAsp1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmailSender" asp-action="Contact">Send Email</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GmailService" asp-action="Index">GmailService</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GmailAPIAsp1 -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>